version: '2.1'

services:
  mysql:
    image: mysql/mysql-server:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: comment_list_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  myapp:
    image: docker.io/bitnami/laravel:latest
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=comment_list_db
    volumes:
      - './my-project:/app'
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local